"""Change NewsLog Model

Revision ID: 046c7b6c14f5
Revises: d37ea880957f
Create Date: 2022-05-13 15:43:10.550840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046c7b6c14f5'
down_revision = 'd37ea880957f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_creating_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('author_name', sa.String(length=2050), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'news', ['author_id'], ['id'])
        batch_op.drop_column('news_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_creating_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('news_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'news', ['news_id'], ['id'])
        batch_op.drop_column('author_name')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
