"""empty message

Revision ID: 1b6eb1024eb5
Revises: 
Create Date: 2022-04-10 15:27:50.884016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b6eb1024eb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('surname', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=2025), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('old', sa.Integer(), nullable=True),
    sa.Column('work', sa.String(length=300), nullable=True),
    sa.Column('img', sa.String(length=2025), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=2050), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('intro', sa.String(length=300), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=300), nullable=True),
    sa.Column('img', sa.String(length=10000), nullable=True),
    sa.Column('file', sa.String(length=10000), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
