"""empty message

Revision ID: a6b5aa251d21
Revises: ee425fd7aed4
Create Date: 2022-03-18 10:29:59.171736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b5aa251d21'
down_revision = 'ee425fd7aed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('news_author', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'news_author')
    # ### end Alembic commands ###
